---
title: Open Savannah
timezone: America/Vancouver
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    layout: post
    comments: true
    social-share: true
- scope:
    path: ''
  values:
    layout: page
    show-avatar: true
url: http://opensavannah.github.io
baseurl: ''
description: A group working to open up public data in Savannah, Ga
navbar-links:
  About:
  - About: about
  - Code of Conduct: codeofconduct
  Resources:
  - OpenDataSav on GitHub: http://github.com/opensavannah
  - OpenDataSav on Meetup.com: https://www.meetup.com/OpenSavannah/
  Join Us: https://www.meetup.com/OpenSavannah/
avatar: http://carlvlewis.s3.amazonaws.com/cvlassets/opendatasav-avatar.png
author:
  name: Carl V. Lewis
  email: carl@opensavannah.org
  facebook: yourname
  github: opensavannah
  twitter: open_savannah
  reddit: yourname
  google-plus: "+yourname"
  linkedin: yourname
  xing: yourname
  stackoverflow: yourlink
  snapchat: yourname
  instagram: yourname
  youtube: yourlink
  spotify: yourname
footer-links-active:
  rss: false
  facebook: false
  email: true
  twitter: true
  google-plus: false
  github: true
  reddit: false
  linkedin: false
  xing: false
  stackoverflow: false
  snapchat: false
  instagram: false
  youtube: false
  spotify: false
share-links-active:
  twitter: true
  facebook: true
  google: true
  linkedin: true
url-pretty: opensavannah.github.io
excerpt_length: 50
markdown: kramdown
highlighter: rouge
permalink: "/:year-:month-:day-:title/"
paginate: 5
kramdown:
  input: GFM
link-tags: false
exclude:
- Gemfile
- Gemfile.lock
- LICENSE
- README.md
- CNAME
- Vagrantfile
prose:
  rooturl: _posts
  media: img
  ignore:
  - 404.html
  - LICENSE
  - feed.xml
  - _config.yml
  - "/_layouts"
  - "/_includes"
  - "/css"
  - "/img"
  - "/js"
  metadata:
    _posts:
    - name: layout
      field:
        element: hidden
        value: post
    - name: title
      field:
        element: text
        label: Post title
        placeholder: Title
        alterable: true
    - name: subtitle
      field:
        element: textarea
        label: Subtitle
        placeholder: A description of your post.
        alterable: true
    - name: date
      field:
        element: text
        label: Date
        help: Enter date of post.
        placeholder: yyyy-mm-dd
        alterable: true
    - name: published
      field:
        element: checkbox
        label: Publish
        help: Check to publish post, uncheck to hide.
gems:
- jekyll-paginate
